### ISSUE TITLE
Error not compiling

### ISSUE THREAD

**Issue by werty100** [omnirom/android_packages_apps_Camera2#3]
It is not compiling:
Note: the configuration keeps the entry point 'com.android.camera.device.MultiCameraDeviceLifecycle { MultiCameraDeviceLifecycle(com.android.camera.device.LegacyCameraActionProvider,com.android.camera.device.PortabilityCameraActionProvider,com.android.camera.device.Camera2ActionProvider,com.android.camera.device.ActiveCameraDeviceTracker,com.android.camera.debug.Logger$Factory); }', but not the descriptor class 'com.android.camera.device.PortabilityCameraActionProvider'
Note: the configuration keeps the entry point 'com.android.camera.device.MultiCameraDeviceLifecycle { MultiCameraDeviceLifecycle(com.android.camera.device.LegacyCameraActionProvider,com.android.camera.device.PortabilityCameraActionProvider,com.android.camera.device.Camera2ActionProvider,com.android.camera.device.ActiveCameraDeviceTracker,com.android.camera.debug.Logger$Factory); }', but not the descriptor class 'com.android.camera.device.Camera2ActionProvider'
Note: the configuration keeps the entry point 'com.android.camera.device.MultiCameraDeviceLifecycle { MultiCameraDeviceLifecycle(com.android.camera.device.LegacyCameraActionProvider,com.android.camera.device.PortabilityCameraActionProvider,com.android.camera.device.Camera2ActionProvider,com.android.camera.device.ActiveCameraDeviceTracker,com.android.camera.debug.Logger$Factory); }', but not the descriptor class 'com.android.camera.device.ActiveCameraDeviceTracker'
Note: the configuration keeps the entry point 'com.android.camera.device.MultiCameraDeviceLifecycle { MultiCameraDeviceLifecycle(com.android.camera.device.LegacyCameraActionProvider,com.android.camera.device.PortabilityCameraActionProvider,com.android.camera.device.Camera2ActionProvider,com.android.camera.device.ActiveCameraDeviceTracker,com.android.camera.debug.Logger$Factory); }', but not the descriptor class 'com.android.camera.debug.Logger$Factory'
Note: the configuration keeps the entry point 'com.android.camera.one.v2.imagesaver.JpegImageBackendImageSaver { JpegImageBackendImageSaver(com.android.camera.one.v2.photo.ImageRotationCalculator,com.android.camera.processing.imagebackend.ImageBackend,java.util.concurrent.Executor,android.graphics.Rect); }', but not the descriptor class 'com.android.camera.one.v2.photo.ImageRotationCalculator'
Note: the configuration keeps the entry point 'com.android.camera.one.v2.imagesaver.JpegImageBackendImageSaver { JpegImageBackendImageSaver(com.android.camera.one.v2.photo.ImageRotationCalculator,com.android.camera.processing.imagebackend.ImageBackend,java.util.concurrent.Executor,android.graphics.Rect); }', but not the descriptor class 'com.android.camera.processing.imagebackend.ImageBackend'
Note: the configuration keeps the entry point 'com.android.camera.one.v2.imagesaver.YuvImageBackendImageSaver { YuvImageBackendImageSaver(com.android.camera.one.v2.photo.ImageRotationCalculator,com.android.camera.processing.imagebackend.ImageBackend,android.graphics.Rect,java.util.concurrent.Executor); }', but not the descriptor class 'com.android.camera.one.v2.photo.ImageRotationCalculator'
Note: the configuration keeps the entry point 'com.android.camera.one.v2.imagesaver.YuvImageBackendImageSaver { YuvImageBackendImageSaver(com.android.camera.one.v2.photo.ImageRotationCalculator,com.android.camera.processing.imagebackend.ImageBackend,android.graphics.Rect,java.util.concurrent.Executor); }', but not the descriptor class 'com.android.camera.processing.imagebackend.ImageBackend'
Note: the configuration keeps the entry point 'com.android.camera.session.CaptureSession { void startSession(com.android.camera.session.CaptureSession$ImageLifecycleListener,android.graphics.Bitmap,int); }', but not the descriptor class 'com.android.camera.session.CaptureSession$ImageLifecycleListener'  GEN     /home/werty100/omni/out/target/product/maguro/obj/KERNEL_OBJ/Makefile

Note: the configuration keeps the entry point 'com.android.camera.stats.CaptureSessionStatsCollector { CaptureSessionStatsCollector(com.android.camera.stats.UsageStatistics); }', but not the descriptor class 'com.android.camera.stats.UsageStatistics'
Note: the configuration keeps the entry point 'com.android.camera.widget.AspectRatioDialogLayout { AspectRatioDialogLayout(android.content.Context,com.android.camera.exif.Rational); }', but not the descriptor class 'com.android.camera.exif.Rational'
Note: the configuration keeps the entry point 'com.google.common.cache.LocalCache { com.google.common.cache.LocalCache$ReferenceEntry newEntry(java.lang.Object,int,com.google.common.cache.LocalCache$ReferenceEntry); }', but not the descriptor class 'com.google.common.cache.LocalCache$ReferenceEntry'
Note: the configuration keeps the entry point 'com.google.common.cache.LocalCache { com.google.common.cache.LocalCache$ReferenceEntry copyEntry(com.google.common.cache.LocalCache$ReferenceEntry,com.google.common.cache.LocalCache$ReferenceEntry); }', but not the descriptor class 'com.google.common.cache.LocalCache$ReferenceEntry'
Note: the configuration keeps the entry point 'com.google.common.cache.LocalCache { com.google.common.cache.LocalCache$ReferenceEntry copyEntry(com.google.common.cache.LocalCache$ReferenceEntry,com.google.common.cache.LocalCache$ReferenceEntry); }', but not the descriptor class 'com.google.common.cache.LocalCache$ReferenceEntry'
Note: the configuration keeps the entry point 'com.google.common.cache.LocalCache { com.google.common.cache.LocalCache$ValueReference newValueReference(com.google.common.cache.LocalCache$ReferenceEntry,java.lang.Object,int); }', but not the descriptor class 'com.google.common.cache.LocalCache$ReferenceEntry'
Note: the configuration keeps the entry point 'com.google.common.cache.LocalCache { boolean isLive(com.google.common.cache.LocalCache$ReferenceEntry,long); }', but not the descriptor class 'com.google.common.cache.LocalCache$ReferenceEntry'
Note: the configuration keeps the entry point 'com.google.common.collect.MapMakerInternalMap { com.google.common.collect.MapMakerInternalMap$ReferenceEntry newEntry(java.lang.Object,int,com.google.common.collect.MapMakerInternalMap$ReferenceEntry); }', but not the descriptor class 'com.google.common.collect.MapMakerInternalMap$ReferenceEntry'
Note: the configuration keeps the entry point 'com.google.common.collect.MapMakerInternalMap { com.google.common.collect.MapMakerInternalMap$ReferenceEntry copyEntry(com.google.common.collect.MapMakerInternalMap$ReferenceEntry,com.google.common.collect.MapMakerInternalMap$ReferenceEntry); }', but not the descriptor class 'com.google.common.collect.MapMakerInternalMap$ReferenceEntry'
Note: the configuration keeps the entry point 'com.google.common.collect.MapMakerInternalMap { com.google.common.collect.MapMakerInternalMap$ReferenceEntry copyEntry(com.google.common.collect.MapMakerInternalMap$ReferenceEntry,com.google.common.collect.MapMakerInternalMap$ReferenceEntry); }', but not the descriptor class 'com.google.common.collect.MapMakerInternalMap$ReferenceEntry'
Note: the configuration keeps the entry point 'com.google.common.collect.MapMakerInternalMap { com.google.common.collect.MapMakerInternalMap$ValueReference newValueReference(com.google.common.collect.MapMakerInternalMap$ReferenceEntry,java.lang.Object); }', but not the descriptor class 'com.google.common.collect.MapMakerInternalMap$ReferenceEntry'
Note: the configuration keeps the entry point 'com.google.common.collect.MapMakerInternalMap { boolean isLive(com.google.common.collect.MapMakerInternalMap$ReferenceEntry); }', but not the descriptor class 'com.google.common.collect.MapMakerInternalMap$ReferenceEntry'
Note: there were 9 references to unknown classes.
      You should check your configuration for typos.
      (http://proguard.sourceforge.net/manual/troubleshooting.html#unknownclass)
Note: there were 2 classes trying to access annotations using reflection.
      You should consider keeping the annotation attributes
      (using '-keepattributes _Annotation_').
      (http://proguard.sourceforge.net/manual/troubleshooting.html#attributes)
Note: there were 16 classes trying to access generic signatures using reflection.
      You should consider keeping the signature attributes
      (using '-keepattributes Signature').
      (http://proguard.sourceforge.net/manual/troubleshooting.html#attributes)
Note: there were 4 classes trying to access enclosing classes using reflection.
      You should consider keeping the inner classes attributes
      (using '-keepattributes InnerClasses').
      (http://proguard.sourceforge.net/manual/troubleshooting.html#attributes)
Note: there were 2 classes trying to access enclosing methods using reflection.
      You should consider keeping the enclosing method attributes
      (using '-keepattributes InnerClasses,EnclosingMethod').
      (http://proguard.sourceforge.net/manual/troubleshooting.html#attributes)
Note: there were 22 unkept descriptor classes in kept class members.
      You should consider explicitly keeping the mentioned classes
      (using '-keep').
      (http://proguard.sourceforge.net/manual/troubleshooting.html#descriptorclass)
Note: there were 2 unresolved dynamic references to classes or interfaces.
      You should check if you need to specify additional program jars.
      (http://proguard.sourceforge.net/manual/troubleshooting.html#dynamicalclass)
Note: there were 10 accesses to class members by means of introspection.
      You should consider explicitly keeping the mentioned class members
      (using '-keep' or '-keepclassmembers').
      (http://proguard.sourceforge.net/manual/troubleshooting.html#dynamicalclassmember)
Warning: there were 119 unresolved references to classes or interfaces.
         You may need to add missing library jars or update their versions.
         If your code works fine without the missing classes, you can suppress
         the warnings with '-dontwarn' options.
         (http://proguard.sourceforge.net/manual/troubleshooting.html#unresolvedclass)
Warning: there were 2 unresolved references to program class members.
         Your input classes appear to be inconsistent.
         You may need to recompile the code.
         (http://proguard.sourceforge.net/manual/troubleshooting.html#unresolvedprogramclassmember)
Error: Please correct the above warnings first.
build/core/java.mk:536: recipe for target '/home/werty100/omni/out/target/common/obj/APPS/Camera2_intermediates/proguard.classes.jar' failed

This happen with more apps

**Comment by Entropy512** [comment]
Your build system has an issue.  As you can see from http://dl.omnirom.org/bullhead/ - Our build system has NO problem building this or any other Omni component.
